In [411]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [412]:
df = pd.read_csv('googleplaystore.csv')
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [413]:
df.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [414]:
df.shape

(10841, 13)

In [415]:
print('Number of Rows:', df.shape[0])
print('Number of Columns:', df.shape[1])

Number of Rows: 10841
Number of Columns: 13

In [416]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [417]:
# overall statistics
df.describe(include='all')

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
count,10841,10841,9367.000000,10841,10841,10841,10840,10841,10840,10841,10841,10833,10838
unique,9660,34,NaN,6002,462,22,3,93,6,120,1378,2832,33
top,ROBLOX,FAMILY,NaN,0,Varies with device,"1,000,000+",Free,0,Everyone,Tools,"August 3, 2018",Varies with device,4.1 and up
freq,9,1972,NaN,596,1695,1579,10039,10040,8714,842,326,1459,2451
mean,NaN,NaN,4.193338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,0.537431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,4.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,4.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,19.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [418]:
# total number of app titles that contain 'astrology'
filt_astrology = df['App'].str.contains('astrology', case=False)
len(df[filt_astrology])

3

In [419]:
df.isnull().sum()
percentage_missing_entries = df.isnull().sum()*100/len(df)
percentage_missing_entries

App                0.000000
Category           0.000000
Rating            13.596532
Reviews            0.000000
Size               0.000000
Installs           0.000000
Type               0.009224
Price              0.000000
Content Rating     0.009224
Genres             0.000000
Last Updated       0.000000
Current Ver        0.073794
Android Ver        0.027673
dtype: float64

In [420]:
# find average app rating
df['Rating'].mean()

4.193338315362448

In [421]:
# find total number of unique category
df['Category'].nunique()

34

In [422]:
# which category is getting the highest average rating
df.groupby('Category')['Rating'].mean().sort_values(ascending=False)

Category
1.9                    19.000000
EVENTS                  4.435556
EDUCATION               4.389032
ART_AND_DESIGN          4.358065
BOOKS_AND_REFERENCE     4.346067
PERSONALIZATION         4.335987
PARENTING               4.300000
GAME                    4.286326
BEAUTY                  4.278571
HEALTH_AND_FITNESS      4.277104
SHOPPING                4.259664
SOCIAL                  4.255598
WEATHER                 4.244000
SPORTS                  4.223511
PRODUCTIVITY            4.211396
HOUSE_AND_HOME          4.197368
FAMILY                  4.192272
PHOTOGRAPHY             4.192114
AUTO_AND_VEHICLES       4.190411
MEDICAL                 4.189143
LIBRARIES_AND_DEMO      4.178462
FOOD_AND_DRINK          4.166972
COMMUNICATION           4.158537
COMICS                  4.155172
NEWS_AND_MAGAZINES      4.132189
FINANCE                 4.131889
ENTERTAINMENT           4.126174
BUSINESS                4.121452
TRAVEL_AND_LOCAL        4.109292
LIFESTYLE               4.094904
VIDEO_PLAYERS           4.063750
MAPS_AND_NAVIGATION     4.051613
TOOLS                   4.047411
DATING                  3.970769
Name: Rating, dtype: float64

In [423]:
# find total number of apps having 5 star rating
filt_app_rating = df['Rating'] == 5
len(df[filt_app_rating]['App'])

274

In [424]:
# find average value of reviews
# df['Reviews'] = pd.to_numeric(df['Reviews'])
# filt = df['Reviews'] == '3.0M'
# df[filt]
df['Reviews'] = df['Reviews'].replace('3.0M', 3.0)
df['Reviews']

0           159
1           967
2         87510
3        215644
4           967
          ...
10836        38
10837         4
10838         3
10839       114
10840    398307
Name: Reviews, Length: 10841, dtype: object

In [425]:
df['Reviews'] = pd.to_numeric(df['Reviews'])
# df['Reviews'].dtypes
df['Reviews'].mean()

444111.9265750392

In [426]:
# total number of free and paid apps
df.Type.value_counts()

Free    10039
Paid      800
0           1
Name: Type, dtype: int64

In [427]:
# which app has max reviews?
# mtd 1
df.groupby('App')['Reviews'].max().sort_values(ascending=False)

App
Facebook                                    78158306.0
WhatsApp Messenger                          69119316.0
Instagram                                   66577446.0
Messenger – Text and Video Chat for Free    56646578.0
Clash of Clans                              44893888.0
                                               ...
CD View                                            0.0
G-NetReport Pro                                    0.0
Summit Medical Video Visits                        0.0
DK Hair Design                                     0.0
ASCP® CG Exam Flashcards 2018                      0.0
Name: Reviews, Length: 9660, dtype: float64

In [428]:
# mtd 2
filt_max_reviews = df['Reviews'] == df['Reviews'].max() 
df[filt_max_reviews]['App']

2544    Facebook
Name: App, dtype: object

In [429]:
# Display top 5 apps having highest reviews
df.groupby('App')['Reviews'].max().sort_values(ascending=False).head()

App
Facebook                                    78158306.0
WhatsApp Messenger                          69119316.0
Instagram                                   66577446.0
Messenger – Text and Video Chat for Free    56646578.0
Clash of Clans                              44893888.0
Name: Reviews, dtype: float64

In [430]:
# find average rating of free and paid apps
df.groupby('Type')['Rating'].mean()

Type
0       19.000000
Free     4.186203
Paid     4.266615
Name: Rating, dtype: float64

In [431]:
df.head(1)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up

In [432]:
# display top 5 apps having max installs
# df['Installs'].astype('float')
# x = df['Installs'].str.replace(',','')
# df = df.insert(6, 'Installs_New', x)
# df.head(1)

In [433]:
df['Installs_1'] = df['Installs'].str.replace(',','')

In [436]:
df['Installs_1'] = df['Installs_1'].str.replace('+','')
df.head(1)

C:\Users\HP\AppData\Local\Temp\ipykernel_30004\1629889509.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Installs_1'] = df['Installs_1'].str.replace('+','')

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Installs_1
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,10000

In [439]:
# df['Installs_1'].astype('float')
filt_free = df['Installs_1'] == 'Free'
df[filt_free]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Installs_1
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN,Free

In [457]:
# df['Installs_1'] = df['Installs_1'].replace('Free', '0')
df['Installs_1'] = df['Installs_1'].replace(to_replace=['Free'], value=['0'])

In [458]:
df['Installs_1'] = df['Installs_1'].astype('float')

In [449]:
df['Installs_1'].max()

1000000000.0

In [459]:
df.groupby('App')['Installs_1'].max().sort_values(ascending=False).head(20)

App
Facebook                                    1.000000e+09
Skype - free IM & video calls               1.000000e+09
Google Drive                                1.000000e+09
Google News                                 1.000000e+09
YouTube                                     1.000000e+09
Google Chrome: Fast & Secure                1.000000e+09
Maps - Navigate & Explore                   1.000000e+09
Subway Surfers                              1.000000e+09
Hangouts                                    1.000000e+09
Google Photos                               1.000000e+09
Google Play Books                           1.000000e+09
Google                                      1.000000e+09
Google Play Games                           1.000000e+09
Gmail                                       1.000000e+09
Messenger – Text and Video Chat for Free    1.000000e+09
Google Play Movies & TV                     1.000000e+09
Google+                                     1.000000e+09
Google Street View                          1.000000e+09
Instagram                                   1.000000e+09
WhatsApp Messenger                          1.000000e+09
Name: Installs_1, dtype: float64

In [453]:
df['Installs_1'].dtype

dtype('float64')